server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://123.57.74.173:3306/liuxin_blog?serverTimezone=GMT%2B8
    username: lxblog
    password: lx200115
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 123.57.74.173
    port: 6379
    connect-timeout: 30000
    password: lx200115

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag  # 逻辑删除， 1 删除 0 不删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto  # 使用雪花算法自动产生id

# 配置加密密钥
jasypt:
  encryptor:
    password: liuxin # TODO 这里密钥修改为自己的！！！
